-- サンプルキャンプ場データの挿入

INSERT INTO campsites (
  id, name_ja, name_en, address_ja, address_en, 
  lat, lng, phone, website, price,
  facilities, activities, 
  nearest_station_ja, nearest_station_en,
  access_time_ja, access_time_en,
  description_ja, description_en,
  price_min, price_max,
  reservation_url, check_in_time, check_out_time, cancellation_policy,
  images
) VALUES (
  '1',
  '高尾の森わくわくビレッジ',
  'Takao Forest Wakuwaku Village',
  '東京都八王子市川町55',
  '55 Kawamachi, Hachioji, Tokyo',
  35.6328,
  139.2644,
  '042-691-1166',
  'https://www.wakuwaku-village.com/',
  '¥2,000-¥4,000/泊',
  ARRAY['toilet', 'shower', 'kitchen', 'bbq', 'parking', 'wifi'],
  ARRAY['hiking', 'bbq', 'stargazing', 'photography'],
  'JR高尾駅',
  'JR Takao Station',
  'バス15分',
  '15 min by bus',
  '高尾山の麓にある自然豊かなキャンプ場。BBQやハイキングを楽しめ、星空観察にも最適です。',
  'A nature-rich campsite at the foot of Mt. Takao. Perfect for BBQ, hiking, and stargazing.',
  2000,
  4000,
  'https://www.wakuwaku-village.com/reservation',
  '14:00',
  '11:00',
  'キャンセル料：利用日の7日前から30%、3日前から50%、当日100%',
  ARRAY[
    'https://images.unsplash.com/photo-1504851149312-7a075b496cc7?w=800',
    'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800',
    'https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?w=800'
  ]
),
(
  '2', 
  '奥多摩湖畔キャンプ場',
  'Lake Okutama Campsite',
  '東京都西多摩郡奥多摩町原5',
  '5 Hara, Okutama, Nishitama, Tokyo',
  35.7891,
  139.0234,
  '0428-86-2556',
  'https://okutama-camp.com/',
  '¥1,500-¥3,500/泊',
  ARRAY['toilet', 'kitchen', 'bbq', 'parking', 'rental'],
  ARRAY['fishing', 'canoe', 'hiking', 'river', 'photography'],
  'JR奥多摩駅',
  'JR Okutama Station',
  'バス20分',
  '20 min by bus',
  '奥多摩湖の美しい景色を楽しめるキャンプ場。釣りやカヌーなどの水上アクティビティが充実しています。',
  'Enjoy the beautiful scenery of Lake Okutama. Rich in water activities such as fishing and canoeing.',
  1500,
  3500,
  'https://okutama-camp.com/booking',
  '13:00',
  '10:00',
  'キャンセル料：利用日の3日前から50%、当日100%',
  ARRAY[
    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800',
    'https://images.unsplash.com/photo-1476041800959-2f6bb412c8ce?w=800'
  ]
),
(
  '3',
  '相模湖プレジャーフォレスト',
  'Sagamiko Pleasure Forest',
  '神奈川県相模原市緑区若柳1634',
  '1634 Wakayanagi, Midori-ku, Sagamihara, Kanagawa',
  35.6045,
  139.2511,
  '042-685-1111',
  'https://www.sagamiko-resort.jp/',
  '¥3,000-¥6,000/泊',
  ARRAY['toilet', 'shower', 'kitchen', 'bbq', 'parking', 'wifi', 'shop'],
  ARRAY['bbq', 'fishing', 'boating', 'cycling', 'hiking'],
  'JR相模湖駅',
  'JR Sagamiko Station',
  'バス8分',
  '8 min by bus',
  '相模湖畔の大型リゾート施設内にあるキャンプ場。遊園地も併設しており、家族連れに人気です。',
  'A campsite within a large resort facility by Lake Sagami. Popular with families as it also has an amusement park.',
  3000,
  6000,
  'https://www.sagamiko-resort.jp/camp/reservation',
  '15:00',
  '10:00',
  'キャンセル料：利用日の7日前から20%、3日前から50%、当日100%',
  ARRAY[
    'https://images.unsplash.com/photo-1508873696983-2dfd5898f08b?w=800',
    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800',
    'https://images.unsplash.com/photo-1445308394109-4ec2920981b1?w=800'
  ]
)
ON CONFLICT (id) DO UPDATE SET
  name_ja = EXCLUDED.name_ja,
  name_en = EXCLUDED.name_en,
  address_ja = EXCLUDED.address_ja,
  address_en = EXCLUDED.address_en,
  lat = EXCLUDED.lat,
  lng = EXCLUDED.lng,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  price = EXCLUDED.price,
  facilities = EXCLUDED.facilities,
  activities = EXCLUDED.activities,
  nearest_station_ja = EXCLUDED.nearest_station_ja,
  nearest_station_en = EXCLUDED.nearest_station_en,
  access_time_ja = EXCLUDED.access_time_ja,
  access_time_en = EXCLUDED.access_time_en,
  description_ja = EXCLUDED.description_ja,
  description_en = EXCLUDED.description_en,
  price_min = EXCLUDED.price_min,
  price_max = EXCLUDED.price_max,
  reservation_url = EXCLUDED.reservation_url,
  check_in_time = EXCLUDED.check_in_time,
  check_out_time = EXCLUDED.check_out_time,
  cancellation_policy = EXCLUDED.cancellation_policy,
  images = EXCLUDED.images;
